apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openapi-aspnetcore-ef6.fullname" . }}
  labels:
    {{- include "openapi-aspnetcore-ef6.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "openapi-aspnetcore-ef6.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "openapi-aspnetcore-ef6.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: runtime-config
          configMap:
            name: {{ include "openapi-aspnetcore-ef6.fullname" . }}
            defaultMode: 420
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "openapi-aspnetcore-ef6.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:latest"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: runtime-config
              mountPath: /tmp/config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
